# .github/workflows/ci.yml

name: CI Workflow

on:
  push: # This workflow will run when code is pushed
  pull_request: # Or when a pull request is created

jobs:
  build:
    runs-on: ubuntu-latest # The runner will be an Ubuntu virtual machine

    steps:
      - name: Checkout code # Step 1: Check out the code from the repository
        uses: actions/checkout@v2

      - name: Set up Node.js # Step 2: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies # Step 3: Install dependencies
        run: npm install

      - name: Run tests # Step 4: Run tests
        run: npm test
